import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom';
import Login from './routes/Login';
import Placeholder from './routes/Placeholder';
import NuevoPedido from './routes/vendedor/NuevoPedido';
import AppShell from './components/AppShell';
import RouteGuard from './components/RouteGuard';
import { useCurrentUser, ROLE_HOME } from './data/auth';
export default function App() {
    const { current, loading } = useCurrentUser();
    if (loading) {
        return (_jsx("div", { className: "min-h-screen flex items-center justify-center text-slate-500", children: "Cargando\u2026" }));
    }
    return (_jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: current ? _jsx(Navigate, { to: ROLE_HOME[current.appUser.role], replace: true }) : _jsx(Login, {}) }), _jsx(Route, { path: "/", element: current ? _jsx(Navigate, { to: ROLE_HOME[current.appUser.role], replace: true }) : _jsx(Navigate, { to: "/login", replace: true }) }), _jsx(Route, { path: "/vendedor/nuevo", element: _jsx(RouteGuard, { current: current, allow: ['vendedor', 'admin', 'superAdmin'], children: _jsx(AppShell, { current: current, children: _jsx(NuevoPedido, {}) }) }) }), _jsx(Route, { path: "/vendedor/mis", element: _jsx(RouteGuard, { current: current, allow: ['vendedor', 'admin', 'superAdmin'], children: _jsx(AppShell, { current: current, children: _jsx(Placeholder, { title: "Mis pedidos", hint: "Llega en el hito 9." }) }) }) }), _jsx(Route, { path: "/despacho/cola", element: _jsx(RouteGuard, { current: current, allow: ['despacho', 'admin', 'superAdmin'], children: _jsx(AppShell, { current: current, children: _jsx(Placeholder, { title: "Cola de despacho", hint: "Llega en el hito 5." }) }) }) }), _jsx(Route, { path: "/produccion", element: _jsx(RouteGuard, { current: current, allow: ['produccion', 'admin', 'superAdmin'], children: _jsx(AppShell, { current: current, children: _jsx(Placeholder, { title: "Producci\u00F3n", hint: "Llega en el hito 6." }) }) }) }), _jsx(Route, { path: "/admin/panel", element: _jsx(RouteGuard, { current: current, allow: ['admin', 'superAdmin'], children: _jsx(AppShell, { current: current, children: _jsx(Placeholder, { title: "Panel de due\u00F1os", hint: "Llega en el hito 8." }) }) }) }), _jsx(Route, { path: "/admin/facturacion", element: _jsx(RouteGuard, { current: current, allow: ['admin', 'superAdmin'], children: _jsx(AppShell, { current: current, children: _jsx(Placeholder, { title: "Facturaci\u00F3n y despacho", hint: "Llega en el hito 7." }) }) }) }), _jsx(Route, { path: "/admin/catalogo", element: _jsx(RouteGuard, { current: current, allow: ['admin', 'superAdmin'], children: _jsx(AppShell, { current: current, children: _jsx(Placeholder, { title: "Cat\u00E1logo y clientes", hint: "Llega en el hito 11." }) }) }) }), _jsx(Route, { path: "/admin/usuarios", element: _jsx(RouteGuard, { current: current, allow: ['superAdmin'], children: _jsx(AppShell, { current: current, children: _jsx(Placeholder, { title: "Usuarios", hint: "Solo Super Administrador. Llega en el hito 11." }) }) }) }), _jsx(Route, { path: "*", element: _jsx(Navigate, { to: "/", replace: true }) })] }) }));
}
